---
kind: auto.CI
spec:
    provider: ghaction
---
kind: common.Image
name: image-roller-derby
spec:
    extraEnvironment:
      PLATFORM: linux/amd64,linux/arm64
---
kind: golang.Build
spec:
  outputs:
    linux-amd64:
      GOOS: linux
      GOARCH: amd64
    linux-arm64:
      GOOS: linux
      GOARCH: arm64
    darwin-amd64:
      GOOS: darwin
      GOARCH: amd64
    darwin-arm64:
      GOOS: darwin
      GOARCH: arm64
---
kind: common.Release
name: release
spec:
  artifacts:
    - roller-derby-*
