name: default
"on":
  push:
    branches:
      - main
      - release-*
    tags:
      - v*
  pull_request:
    branches:
      - main
      - release-*
jobs:
  default:
    strategy:
      matrix:
        include:
          - runner: X64
            platform: linux/amd64
          - runner: ARM64
            platform: linux/arm64
    permissions:
      packages: write
    runs-on:
      - self-hosted
      - ${{ matrix.runner }}
    if: ${{ !startsWith(github.head_ref, 'renovate/') || !startsWith(github.head_ref, 'renovate/') }}
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - uses: imjasonh/setup-crane@v0.3
      - name: Unshallow
        run: |
          git fetch --prune --unshallow
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          config-inline: |
            [worker.oci]
              gc = true
              gckeepstorage = 100000 # 100 GiB

              [[worker.oci.gcpolicy]]
                keepBytes = 32212254720 # 30 GiB
                keepDuration = 604800
                filters = [ "type==source.local", "type==exec.cachemount", "type==source.git.checkout"]
              [[worker.oci.gcpolicy]]
                all = true
                keepBytes = 107374182400 # 100 GiB
      - name: build
        run: |
          make PLATFORM=${{ matrix.platform }}
      - name: Login to registry
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v2
        with:
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: ghcr.io
          username: ${{ github.repository_owner }}
      - name: push-local
        if: github.event_name != 'pull_request'
        run: |
          make PLATFORM=${{ matrix.platform }}
        env:
          PUSH: true
          REGISTRY: registry.dev.siderolabs.io
      - name: push
        if: github.event_name != 'pull_request'
        run: |
          make push
        env:
          PUSH: true
          REGISTRY: registry.dev.siderolabs.io
