name: default
"on":
  push:
    branches:
      - main
    tags:
      - v*
  pull_request: {}
env:
  CI_ARGS: --cache-from=type=registry,ref=registry-registry-dev-talos-systems-io.ci.svc.cluster.local:5000/${GITHUB_REPOSITORY}:buildcache --cache-to=type=registry,ref=registry-registry-dev-talos-systems-io.ci.svc.cluster.local:5000/${GITHUB_REPOSITORY}:buildcache,mode=max
jobs:
  default:
    permissions:
      contents: write
      packages: write
    runs-on: self-hosted
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: Unshallow
        run: |
          git fetch --prune --unshallow
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          config-inline: |
            [registry."registry-registry-dev-talos-systems-io.ci.svc.cluster.local:5000"]
              http = true
      - name: base
        run: |
          make base
      - name: unit-tests
        run: |
          make unit-tests
      - name: unit-tests-race
        run: |
          make unit-tests-race
      - name: coverage
        run: |
          make coverage
      - name: roller-derby
        run: |
          make roller-derby
      - name: lint
        run: |
          make lint
      - name: Login to registry
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v2
        with:
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: ghcr.io
          username: ${{ github.repository_owner }}
      - name: image-roller-derby
        run: |
          make image-roller-derby
      - name: push-roller-derby
        if: github.event_name != 'pull_request'
        env:
          PLATFORM: linux/amd64,linux/arm64
          PUSH: "true"
        run: |
          make image-roller-derby
      - name: push-roller-derby-latest
        if: github.event_name != 'pull_request'
        env:
          PLATFORM: linux/amd64,linux/arm64
          PUSH: "true"
        run: |
          make image-roller-derby TAG=latest
      - name: release-notes
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          make release-notes
      - name: Generate sha256 checksum
        if: startsWith(github.ref, 'refs/tags/')
        uses: jmgilman/actions-generate-checksum@v1
        with:
          method: sha256
          output: _out/sha256sum.txt
          patterns: |
            _out/roller-derby-*
      - name: Generate sha512 checksum
        if: startsWith(github.ref, 'refs/tags/')
        uses: jmgilman/actions-generate-checksum@v1
        with:
          method: sha512
          output: _out/sha512sum.txt
          patterns: |
            _out/roller-derby-*
      - name: Release
        if: startsWith(github.ref, 'refs/tags/')
        uses: ncipollo/release-action@v1
        with:
          artifacts: _out/roller-derby-*,sha*.txt
          bodyFile: _out/RELEASE_NOTES.md
          draft: "true"
