name: ci

on:
  push:

jobs:
  buildx:
    runs-on: self-hosted
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: buildx setup
        uses: docker/setup-buildx-action@v2

      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3