name: default
"on":
  push:
    branches:
      - main
    tags:
      - v*
  pull_request: {}
env:
  CI_ARGS: --cache-from=type=registry,ref=registry.dev.siderolabs.io/${GITHUB_REPOSITORY}:buildcache --cache-to=type=registry,ref=registry.dev.siderolabs.io/${GITHUB_REPOSITORY}:buildcache,mode=max
jobs:
  default:
    if: ${{ !startsWith(github.head_ref, 'renovate/') || !startsWith(github.head_ref, 'renovate/') }}
    permissions:
      contents: write
      packages: write
    runs-on:
      - self-hosted
      - X64
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: Unshallow
        run: |
          git fetch --prune --unshallow
