name: e2e-full-cron
concurrency:
  group: ${{ github.head_ref || github.run_id }}
  cancel-in-progress: true
"on":
  schedule:
    - cron: */5 * * * *
jobs:
  default:
    runs-on:
      - self-hosted
      - generic
    steps:
      - name: checkout
        uses: actions/checkout@v4
